require conf/distro/poky.conf

DISTRO = "pyronear-os"
DISTRO_NAME = "PyroNear OS"
DISTRO_VERSION = "1.0"

# Disable all default DISTRO_FEATURES
DISTRO_FEATURES_OPTED_OUT = "*"

# Distro features required by the Pyronear environment
DISTRO_FEATURES:append = " \
    wifi \
    ipv6 \
    \
    virtualization \
    seccomp \
    \
    overlayfs \
    rauc \
"

INIT_MANAGER = "systemd"
