require conf/distro/poky.conf

DISTRO = "pyronear-os"
DISTRO_NAME = "PyroNear OS"
DISTRO_VERSION = "1.0"

INIT_MANAGER = "systemd"

# --- DISTRO & MACHINE FEATURES ---
DISTRO_FEATURES:append = " virtualization"
DISTRO_FEATURES:remove = " x11 wayland opengl vulkan alsa bluetooth nfc pcmcia ptest debuginfod zeroconf nfs usbgadget multiarch"

DISTRO_FEATURES:append = " overlayfs"
DISTRO_FEATURES:append = " rauc"

# --- LICENCES & CONSOLES ---
LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

# --- HARDWARE & RASPBERRY PI TWEAKS ---
KERNEL_MODULE_AUTOLOAD += "zram"
