#Type   Path                    Mode  User    Group   Age  Argument
d       /data/home/engine       0775  engine  engine  -    -
d       /data/home/engine/data  0775  engine  engine  -    -

d       /data/pyro-engine-src   0755  root    root    -    -