FILESEXTRAPATHS:prepend:rpi := "${THISDIR}/files:"

SRC_URI += "file://fstab.fragment"

# Append custom entries to the default fstab generated by Yocto
do_install:append() {
    cat ${UNPACKDIR}/fstab.fragment >> ${D}${sysconfdir}/fstab
}