# Type  Chemin                     Mode  User    Group   Age  Argument
# Éspace d'exécution et sockets des démons (Droit strict 0711)
d       /data/docker                0711  root    root    -    -
d       /data/containerd            0711  root    root    -    -
d       /data/dropbear              0750  root    root    -    -

# Éspace Runtime Applicatif (Nécessite le groupe docker pour les volumes/conteneurs)
d       /data/pyro-engine-home      0775  engine  docker  -    -
d       /data/pyro-engine-home/data 0775  engine  docker  -    -

# Éspace Source Git (Isolé de Docker, droits standards 0755)
d       /data/pyro-engine-src       0755  engine  engine  -    -

# Réapplication récursive des droits au boot
Z       /data/pyro-engine-home      0775  engine  docker  -    -
Z       /data/pyro-engine-src       0755  engine  engine  -    -