require conf/machine/raspberrypi5.conf

MACHINEOVERRIDES =. "raspberrypi5:"

RPI_USE_U_BOOT = "1"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
SDIMG_KERNELIMAGE:raspberrypi5 = "u-boot.bin"
IMAGE_BOOT_FILES:append = " u-boot.bin;kernel_2712.img Image"

# Enable serial port for debugging and communication
ENABLE_UART = "1"
RPI_EXTRA_CONFIG:append = "\nkernel=u-boot.bin"
RPI_EXTRA_CONFIG:append = "\ndtoverlay=uart0-pi5"
RPI_EXTRA_CONFIG:append = "\nuart_2ndstage=1"
RPI_EXTRA_CONFIG:append = "\narm_64bit=1"

SERIAL_CONSOLES = "115200;ttyAMA0"

MACHINE_FEATURES:remove = " screen touchscreen alsa bluetooth"

# Overlayfs-etc configuration
OVERLAYFS_ETC_MOUNT_POINT = "/data"
OVERLAYFS_ETC_FSTYPE = "ext4"
OVERLAYFS_ETC_DEVICE = "/dev/mmcblk0p4"