require conf/machine/raspberrypi5.conf

MACHINEOVERRIDES =. "raspberrypi5:"

# Activation de l'UART pour la communication série
ENABLE_UART = "1"
RPI_EXTRA_CONFIG:append = " dtoverlay=uart0-pi5"
SERIAL_CONSOLES = "115200;ttyAMA0"

MACHINE_FEATURES:remove = " screen touchscreen alsa bluetooth"