# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-pyronear"
BBFILE_PATTERN_meta-pyronear = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-pyronear = "6"

LAYERDEPENDS_meta-pyronear = " \
    core \
    raspberrypi \
    virtualization-layer \
    rauc \
"

LAYERSERIES_COMPAT_meta-pyronear = "wrynose"
